# Site settings
title: 门不存在
header-img: "img/facebook.jpg"
tagline: "cn"  
description: "Edward|出来混·迟早还"  
baseurl: ""
url: "http://lfl2.xyz"  

# About/contact
owner: 
  name: " Edward  "
  email: echoxi@gqq.com
  bio: "门不存在，不要温柔的走进那个良夜"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.png

douban_username:  Edward
twitter_username: Edward
github_username: Edwardvi
facebook_username: 
weibo_username: Edward
zhihu_username: yinsi

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
relative_permalinks: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Edward"
      header-img: "img/facebook.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : Edward
  disqus :
      short_name : Edward

# Analytics and webmaster tools stuff goes here
google_analytics: 
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
